name: clean_arc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  # Flutter SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  dartz: ^0.10.1

  # Navigation
  go_router: ^14.8.1

  # Networking & APIs
  dio: ^5.8.0+1

  # Internationalization
  intl: any

  # App Preview & Utilities
  device_preview: ^1.2.0
  app_rename: ^0.0.1

  # Icons and Launchers
  flutter_launcher_icons: ^0.14.4

  # UI Components and Styling
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  persistent_bottom_nav_bar: ^6.2.1
  dots_indicator: ^4.0.1
  percent_indicator: ^4.2.5

dev_dependencies:
  # Linting
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.1

  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.1

  # Analyzer Plugins (manual pins to avoid conflicts)
  analyzer: 6.11.0
  analyzer_plugin: 0.11.3

  # Flutter Testing
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraLight.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf

  # Asset folders
  assets:
    - assets/fonts/Cairo/
    - assets/fonts/Roboto/

    - assets/icons/App_Icon/

    - assets/imgs/
    
    - assets/jsons/
